name: Retrieve Secrets from Vault

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Vault CLI
      run: |
        curl -fsSL https://releases.hashicorp.com/vault/1.11.0/vault_1.11.0_linux_amd64.zip -o vault.zip
        unzip vault.zip
        sudo mv vault /usr/local/bin/

    - name: Authenticate with Vault
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}  # Set Vault server address (can be stored as a GitHub secret)
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}  # Set the Vault token (can be stored as a GitHub secret)
      run: |
        vault login $VAULT_TOKEN

    - name: Retrieve secrets from Vault
      run: |
        client_id=$(vault kv get -field=client_id secret/github-actions/azure)
        container_name=$(vault kv get -field=container_name secret/github-actions/azure)
        resource_group_name=$(vault kv get -field=resource_group_name secret/github-actions/azure)
        storage_account=$(vault kv get -field=storage_account secret/github-actions/azure)
        subscription_id=$(vault kv get -field=subscription_id secret/github-actions/azure)
        tenant_id=$(vault kv get -field=tenant_id secret/github-actions/azure)

        echo "client_id: $client_id"
        echo "container_name: $container_name"
        echo "resource_group_name: $resource_group_name"
        echo "storage_account: $storage_account"
        echo "subscription_id: $subscription_id"
        echo "tenant_id: $tenant_id"
