name: Retrieve Secrets from Vault

on: push

permissions:
    id-token: write
    contents: read 

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Retrieve Secret
      id: secretdata
      uses: hashicorp/vault-action@v2.4.0
      with:
        method: jwt
        url: "https://${{ secrets.VAULT_ADDR }}"
        role: "github-actions"
        secrets: |
            ${{ secrets.VAULT_SECRET_PATH }} ${{ secrets.VAULT_SECRET_KEY }} | client_id

    
    - name: Print Secret Data
      run: |
        echo 'CLIENT_ID: ${{ steps.secretdata.outputs.client_id }}'
        
    